version: '3'

services:
    wordpress:
        depends_on:
            - mysqldb
        image: wordpress:latest
        links:
            - mysqldb:mysql
        volumes:
            - ./wordpress/wp-content:/var/www/html/wp-content
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

    mysqldb:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secretpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysqldb:mysql
        ports:
            - 8181:80
        environment:
            PMA_HOST: mysql

volumes:
    db_data:
